/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import javax.script.*;
/**
 *
 * @author My PC
 */
public class CalculatorSystem extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorSystem
     */
    public CalculatorSystem() {
        initComponents();
        Result.setEditable(false); // Cấm người dùng chỉnh sửa Fields kết quả 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PhepTinh = new javax.swing.ButtonGroup();
        Close = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        EnterNumberB = new javax.swing.JTextField();
        EnterNumberA = new javax.swing.JTextField();
        NumberA = new javax.swing.JLabel();
        NumberB = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Plus = new javax.swing.JRadioButton();
        Subtract = new javax.swing.JRadioButton();
        Multiply = new javax.swing.JRadioButton();
        Divide = new javax.swing.JRadioButton();
        Solve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Result = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close.setBackground(new java.awt.Color(255, 255, 102));
        Close.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Close.setForeground(new java.awt.Color(255, 51, 51));
        Close.setText("CLOSE");
        Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 70, 40));

        Title.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 255, 255));
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SrcImage/calculator.png"))); // NOI18N
        Title.setText("CACULATOR");
        Title.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        EnterNumberB.setBackground(new java.awt.Color(204, 255, 255));
        EnterNumberB.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));
        EnterNumberB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNumberBActionPerformed(evt);
            }
        });
        getContentPane().add(EnterNumberB, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 120, 260, 40));

        EnterNumberA.setBackground(new java.awt.Color(204, 255, 255));
        EnterNumberA.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 0)));
        EnterNumberA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNumberAActionPerformed(evt);
            }
        });
        getContentPane().add(EnterNumberA, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 60, 260, 40));

        NumberA.setBackground(new java.awt.Color(204, 0, 0));
        NumberA.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        NumberA.setForeground(new java.awt.Color(255, 255, 255));
        NumberA.setText("NUMBER A:");
        getContentPane().add(NumberA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        NumberB.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        NumberB.setForeground(new java.awt.Color(255, 255, 255));
        NumberB.setText("NUMBER B:");
        getContentPane().add(NumberB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Reset.setBackground(new java.awt.Color(102, 255, 102));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Reset.setForeground(new java.awt.Color(0, 153, 51));
        Reset.setText("RESET");
        Reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 90, 40));

        PhepTinh.add(Plus);
        Plus.setForeground(new java.awt.Color(0, 255, 0));
        Plus.setText("PLUS ( A+B)");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });
        getContentPane().add(Plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 20));

        PhepTinh.add(Subtract);
        Subtract.setForeground(new java.awt.Color(255, 255, 51));
        Subtract.setText("SUBTRACT (A-B)");
        Subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractActionPerformed(evt);
            }
        });
        getContentPane().add(Subtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        PhepTinh.add(Multiply);
        Multiply.setForeground(new java.awt.Color(0, 255, 204));
        Multiply.setText("MULTIPLY (A*B)");
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(Multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        PhepTinh.add(Divide);
        Divide.setForeground(new java.awt.Color(204, 102, 0));
        Divide.setText("DIVIDE (A/B)");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });
        getContentPane().add(Divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        Solve.setBackground(new java.awt.Color(102, 255, 102));
        Solve.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Solve.setForeground(new java.awt.Color(255, 255, 51));
        Solve.setText("SOLVE");
        Solve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveActionPerformed(evt);
            }
        });
        getContentPane().add(Solve, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 130));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESULT:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 60, -1));

        Result.setBackground(new java.awt.Color(204, 255, 255));
        Result.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 153), 1, true));
        Result.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        getContentPane().add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 180, 40));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SrcImage/wallpaperflare-cropped (1).jpg"))); // NOI18N
        Background.setLabelFor(this);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    private void EnterNumberBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNumberBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterNumberBActionPerformed
    //Code của Reset button
    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        EnterNumberA.setText(" ");
        EnterNumberB.setText(" ");
        Result.setText(" ");
    }//GEN-LAST:event_ResetActionPerformed

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseMouseClicked

    private void SubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubtractActionPerformed

    private void EnterNumberAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNumberAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterNumberAActionPerformed

    private void SolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveActionPerformed
        // TODO add your handling code here:qe
            // Lấy giá trị trong s1 và s2
           
//            String s1Text = EnterNumberA.getText();
//            String s2Text = EnterNumberB.getText();
//            // Thực hiện phép tính
//            if(Plus.isSelected()){
//                double result1 = evaluate(s1Text) + evaluate(s2Text);
//                Result.setText(Double.toString(result1));
//            }else if (Subtract.isSelected()){
//                 double result1 = evaluate(s1Text) - evaluate(s2Text);
//                Result.setText(Double.toString(result1));
//            }else if(Multiply.isSelected()){
//                double result1 = evaluate(s1Text) * evaluate(s2Text);
//                Result.setText(Double.toString(result1));
//            }else if(Divide.isSelected()){
//                if(evaluate(s2Text)==0) Result.setText("Can't Solve!!!");
//                else {
//                    double result1 = evaluate(s1Text) / evaluate(s2Text);
//                    Result.setText(Double.toString(result1));
//                }
//            }

       try {
           // lấy giá trị a và b
            double a;
            double b;
            a = Double.parseDouble(EnterNumberA.getText());
            b = Double.parseDouble(EnterNumberB.getText());
            // tính toán theo giá trị và người dùng nhập vào 
            if(Plus.isSelected())Result.setText(" "+(a+b));
            else if(Subtract.isSelected())Result.setText(" "+(a-b));
        
            else if(Multiply.isSelected())Result.setText(" "+(a*b));
        
            else if(Divide.isSelected()){if(b==0)Result.setText("Can't Solve");
        
            else Result.setText(" "+(a/b));
        }
           
    } catch (NumberFormatException e){
         Result.setText("!!! Incorrect format !!!");
    }
    }//GEN-LAST:event_SolveActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultiplyActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DivideActionPerformed

    /**
     * @param args the command line arguments
     */
    //hàm evaluate dùng để tính toán chuỗi phép tính đc nhập vào 
//private double evaluate(String n) {
//        double result1=0;
//        try {
//            result1 = Double.parseDouble(n);
//        } catch (NumberFormatException e) {
//            // Nếu expression không phải là một số, thực hiện phép tính
//            ScriptEngineManager mgr = new ScriptEngineManager();
//            ScriptEngine engine = mgr.getEngineByName("js");
//            try{
//               result1 = (double) engine.eval(n);
//            } catch (ScriptException ex){
//            }
//        }
//        return result1;
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorSystem().setVisible(true);
                
            }
        });
    }
    
// khởi tạo các button và fields và gán tên cho những thành phần này
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Close;
    private javax.swing.JRadioButton Divide;
    private javax.swing.JTextField EnterNumberA;
    private javax.swing.JTextField EnterNumberB;
    private javax.swing.JRadioButton Multiply;
    private javax.swing.JLabel NumberA;
    private javax.swing.JLabel NumberB;
    private javax.swing.ButtonGroup PhepTinh;
    private javax.swing.JRadioButton Plus;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField Result;
    private javax.swing.JButton Solve;
    private javax.swing.JRadioButton Subtract;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

       
}
